module.exports = Object.freeze({
    COPYRIGHT: 'Copyright 2023 Aspirant Technology',
    COPYRIGHTEMAIL: 'karki22mahesh@gmail.com ',
    SOURCE:"pointer\":\"/data/attributes/",
    CODE:'code',
    VERSION:'1.1',
    PAYLOADDETAIL:'Version is missing in api payload.',
    PAYLOADTITLE:'Payload is not valid.',
    METAPAYLOADDETAIL:'Either copyright,email or api is missing in meta payload.',
    METAPAYLOADTITLE:'MetaPayload is not valid.',
    METADATAPAYLOADDETAIL:'Missing `data` or meta Member at document\'s top level.',
    METADATAPAYLOADTITLE:'Meta or Data Payload is not valid',
    COMMONERROR:'Something went wrong',
    MAINTENANCEMODEMESSAGE : "Sorry, the server is under maintenance. Please try again later.",
    MAINTENANCEMODETITLE : "Maintenance Mode",
    CUSTOMERCAREMESSAGE : "%message%",
    INVALIDCREDENTIALS: "Invalid credentials",
    INVALIDPASSWORD: "invalid password",
    INVALIDACCOUNT: "Invalid account",
    INVALIDTOKEN: "invalid token",
    EXPIREDTOKEN: "Token expired",
    USERNOTFOUND: "user not found",
    USERNAMEPASSWORDINCORRECT: "error from cath",
    EMAILISREQUIRED: "Email is required",
    PASSWORDISREQUIRED: "Password is required",
    USERNOTFOUNDLOGINBYFACEBOOK: "Please login via facebook since your account is linked with it.",
    USERNOTFOUNDLOGINBYAPPLE: "Please login via apple since your account is linked with it.",
    INVALIDREFRESHTOKEN: "Invalid refresh token. Please login.",
    USEREMAILALREADYEXISTS: "User with email already exists in system.",
    PASSWORDUPDATESUCCESSFULLY: "Password updated successfully.",
    EMAILCONFIRMSUCCESSFULLY: "Email confirmed successfully.",
    SUBSCRIPTIONSTATUSISINACTIVE: "Subscription status is inactive.",
    SOMETHINGWENTWRONG: "something went wrong.",
    INVALIDREFRESHTOKEN: "invalid  Refresh token",


});