module.exports = Object.freeze({
    COPYRIGHT: 'Copyright 2022 Brasso',
    COPYRIGHTEMAIL: 'info@brasso.com ',
    SOURCE:"pointer\":\"/data/attributes/",
    CODE:'code',
    VERSION:'1.1',
    PAYLOADDETAIL:'Version is missing in api payload.',
    PAYLOADTITLE:'Payload is not valid.',
    METAPAYLOADDETAIL:'Either copyright,email or api is missing in meta payload.',
    METAPAYLOADTITLE:'MetaPayload is not valid.',
    METADATAPAYLOADDETAIL:'Missing `data` or meta Member at document\'s top level.',
    METADATAPAYLOADTITLE:'Meta or Data Payload is not valid',
    COMMONERROR:'Something went wrong',
    MAINTENANCEMODEMESSAGE : "Sorry, the server is under maintenance. Please try again later.",
    MAINTENANCEMODETITLE : "Maintenance Mode",
    CUSTOMERCAREMESSAGE : "%message%",
    INVALIDCREDENTIALS: "Invalid credentials",
    INVALIDPASSWORD: "パスワードが違います",
    ACCOUNTDEACTIVATED: "アカウントが無効になっています。管理者にお問い合わせください。.",
    INVALIDACCOUNT: "Invalid account",
    INVALIDTOKEN: "無効なトークン",
    EXPIREDTOKEN: "Token expired",
    USERNOTFOUND: "ユーザーが見つかりません",
    USERNAMEPASSWORDINCORRECT: "ユーザーまたはパスワードが違います",
    EMAILISREQUIRED: "メールアドレスは必須です",
    PASSWORDISREQUIRED: "パスワードは必須です",
    USERNOTFOUNDLOGINBYFACEBOOK: "Please login via facebook since your account is linked with it.",
    USERNOTFOUNDLOGINBYAPPLE: "Please login via apple since your account is linked with it.",
    INVALIDREFRESHTOKEN: "Invalid refresh token. Please login.",
    USEREMAILALREADYEXISTS: "User with email already exists in system.",
    PASSWORDUPDATESUCCESSFULLY: "Password updated successfully.",
    EMAILCONFIRMSUCCESSFULLY: "Email confirmed successfully.",
    SUBSCRIPTIONSTATUSISINACTIVE: "Subscription status is inactive.",
    SOMETHINGWENTWRONG: "何らかの不都合が発生しました.",
    PRODUCTALREADYOWNED: "有料コンテンツは既に購入済です",

    EMAIL_CODE: {
        ACTIVATION: "email_verification",
        NEWACCOUNT: "cms_user_email_verification",
        FORGOTPASSWORD: "forgot_password",
        NEWSLETTER: "news_letter_email_verification",
        VERIFIEDEMAIL: "news_letter_email_verified",
        STOREEMAIL: "store_user_detail_email"
    }
});